version: '3.8'

services:
  neo4j:
    image: neo4j:5.19
    container_name: neo4j
    ports:
      - "7687:7687"
      - "7474:7474"
    environment:
      NEO4J_AUTH: neo4j/neo4jneo4j
      NEO4J_PLUGINS: '["apoc"]'
    volumes:
      - neo4j_data:/data
      - neo4j_plugins:/plugins

volumes:
  neo4j_data:
  neo4j_plugins:
